In [13]:
import pandas as pd

In [54]:
dataset = pd.read_csv("2020-2021_Assessment_Roll.csv")
dataset

,SBL,Tax District,Print Key,Front,Depth,Property Class,Property Class Description,Previous Property Class,Owner1,Owner2,...,# of Kitchens,Council District,Police District,Census Tract,Census Block Group,Census Block,Neighborhood,Latitude,Longitude,Location
0,1016500006006110,147012,101.65-6-6.11,45.00,107.30,210,ONE FAMILY DWELLING,210.0,JONES GLORIA,NaN,...,1,LOVEJOY,District C,30002.0,2.0,2005.0,Genesee-Moselle,42.904611,-78.808214,POINT (-78.8082142214 42.9046111309)
1,1111700016001110,147001,111.17-16-1.11,930.00,525.00,590,PARKS,590.0,CITY OF BUFFALO DIVISION OF,NaN,...,0,FILLMORE,District B,165001.0,1.0,1135.0,Central,42.887618,-78.874311,POINT (-78.8743109952 42.8876180631)
2,1112500004013100,147003,111.25-4-13.1,292.95,100.00,620,RELIGIOUS,620.0,GETHSEMANE BAPTIST CHURCH,NaN,...,0,ELLICOTT,District B,31002.0,2.0,2012.0,Fruit Belt,42.897104,-78.856519,POINT (-78.8565187367 42.8971044751)
3,1013800003039000,147011,101.38-3-39,30.00,119.00,311,RESIDENTIAL VACANT LAND,311.0,BARNES KEITH,NaN,...,0,MASTEN,District C,35003.0,3.0,3001.0,MLK Park,42.911783,-78.825654,POINT (-78.8256543801 42.9117825692)
4,1014500001056000,147005,101.45-1-56,30.00,117.00,311,RESIDENTIAL VACANT LAND,311.0,BEAL ISAAC & W,NaN,...,0,MASTEN,District C,35002.0,2.0,2000.0,MLK Park,42.911543,-78.834795,POINT (-78.834794801 42.9115429975)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93716,0995200006006000,147002,99.52-6-6,29.00,137.42,210,ONE FAMILY DWELLING,210.0,POWELL BECKY,NaN,...,1,NIAGARA,District B,67012.0,2.0,2002.0,Elmwood Bryant,42.908895,-78.883737,POINT (-78.8837371364 42.9088953341)
93717,0995900004009000,147002,99.59-4-9,31.42,149.00,210,ONE FAMILY DWELLING,210.0,TORINA EDWARD V,NaN,...,1,NIAGARA,District B,69012.0,2.0,2003.0,West Side,42.908620,-78.889393,POINT (-78.8893926744 42.9086195755)
93718,0908200001043000,147011,90.82-1-43,60.00,102.00,220,TWO FAMILY DWELLING,220.0,CITY OF BUFFALO PERFECTING TIT,NaN,...,2,LOVEJOY,District E,37001.0,1.0,1001.0,Schiller Park,42.921905,-78.807481,POINT (-78.8074806481 42.9219050281)
93719,0993400004030000,147007,99.34-4-30,50.00,83.00,411,APARTMENT,411.0,ROBERTS NICOLE,NaN,...,0,NIAGARA,District D,61005.0,5.0,5005.0,Upper West Side,42.915350,-78.895746,POINT (-78.8957457215 42.9153504871)
93720,0906600001004000,147010,90.66-1-4,44.00,110.00,220,TWO FAMILY DWELLING,220.0,TRUESDALE JASON,NaN,...,2,UNIVERSITY,District E,44022.0,2.0,2006.0,Kenfield,42.928556,-78.808411,POINT (-78.8084107105 42.9285555073)

In [55]:
columns = ["Print Key", "Previous Property Class", "Owner2", "Mail1", "Mail2", "Zipcode Extension", "Year Built", "Overall Condition", "Building Style", "Heat Type", "Basement Type", "# of Stories", "# of Fireplaces", "# of Beds", "# of Baths", "# of Kitchens","Location"]
dataset = dataset.drop(columns = columns)

In [56]:
dataset = dataset.dropna()

In [57]:
dataset.shape

(70900, 34)

In [58]:
# Checking for null values in the dataset
null_values = dataset.isnull().sum()

# Displaying columns with null values (if any)
print(null_values[null_values > 0])

Series([], dtype: int64)

In [59]:
dataset.dtypes

SBL                            object
Tax District                    int64
Front                         float64
Depth                         float64
Property Class                  int64
Property Class Description     object
Owner1                         object
Previous Owner                 object
Mail3                          object
Mail4                          object
House Number                    int64
Street                         object
Address                        object
City                           object
State                          object
Zipcode                       float64
Deed Book                     float64
Deed Page                     float64
Deed Date                      object
Roll                            int64
Land Value                      int64
Total Value                     int64
Sale Price                      int64
First Story Area                int64
Second Story Area               int64
Total Living Area               int64
Council District               object
Police District                object
Census Tract                  float64
Census Block Group            float64
Census Block                  float64
Neighborhood                   object
Latitude                      float64
Longitude                     float64
dtype: object

In [60]:
dataset["Zipcode"] = dataset["Zipcode"].astype(str)
dataset["Index"] = range(1, len(dataset) + 1)
dataset = dataset[:25000]

In [61]:
dataset.shape

(25000, 35)

In [62]:

# Read the CSV file into a DataFrame
df = pd.read_csv("data-1710689984270.csv")  # Replace "your_file.csv" with the path to your CSV file

df

    house_number  zipcode          street
0            378  14211.0           URBAN
1             65  14201.0         WHITNEY
2            309  14201.0        NORTH ST
3             84  14202.0          OJIBWA
4             33  14202.0        FRANKLIN
5           1119  14209.0        DELAWARE
6            170  14209.0     LINWOOD AVE
7             40  14202.0  WATERFRONT CIR
8           1141  14209.0        DELAWARE
9            610  14202.0            MAIN
10           216  14222.0          SUMMER
11            75  14202.0          OJIBWA
12           233  14222.0        RICHMOND
13           770  14222.0      FERRY WEST
14           391  14203.0      WASHINGTON
15            82  14202.0          OJIBWA
16           200  14202.0        DELAWARE
17           132  14202.0       LAKEFRONT
18           666  14222.0      FERRY WEST
19           800  14222.0      FERRY WEST
20           125  14201.0          EDWARD
21           900  14209.0        DELAWARE
22          1088  14209.0        DELAWARE
23           125  14202.0          EDWARD
24           849  14209.0        DELAWARE

In [63]:
# Define the condition for the record to be removed
# Define the conditions for deletion
#repeated records
conditions = [
    (dataset["House Number"] == 378) & (dataset["Zipcode"] == "14211.0") & (dataset["Street"] == "URBAN"),
    (dataset["House Number"] == 65) & (dataset["Zipcode"] == "14201.0") & (dataset["Street"] == "WHITNEY"),
    (dataset["House Number"] == 309) & (dataset["Zipcode"] == "14201.0") & (dataset["Street"] == "NORTH ST"),
    (dataset["House Number"] == 84) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "OJIBWA"),
    (dataset["House Number"] == 33) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "FRANKLIN"),
    (dataset["House Number"] == 1119) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "DELAWARE"),
    (dataset["House Number"] == 170) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "LINWOOD AVE"),
    (dataset["House Number"] == 40) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "WATERFRONT CIR"),
    (dataset["House Number"] == 1141) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "DELAWARE"),
    (dataset["House Number"] == 610) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "MAIN"),
    (dataset["House Number"] == 216) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "SUMMER"),
    (dataset["House Number"] == 75) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "OJIBWA"),
    (dataset["House Number"] == 233) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "RICHMOND"),
    (dataset["House Number"] == 770) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "FERRY WEST"),
    (dataset["House Number"] == 391) & (dataset["Zipcode"] == "14203.0") & (dataset["Street"] == "WASHINGTON"),
    (dataset["House Number"] == 82) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "OJIBWA"),
    (dataset["House Number"] == 200) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "DELAWARE"),
    (dataset["House Number"] == 132) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "LAKEFRONT"),
    (dataset["House Number"] == 666) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "FERRY WEST"),
    (dataset["House Number"] == 800) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "FERRY WEST"),
    (dataset["House Number"] == 125) & (dataset["Zipcode"] == "14201.0") & (dataset["Street"] == "EDWARD"),
    (dataset["House Number"] == 900) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "DELAWARE"),
    (dataset["House Number"] == 1088) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "DELAWARE"),
    (dataset["House Number"] == 125) & (dataset["Zipcode"] == "14202.0") & (dataset["Street"] == "EDWARD"),
    (dataset["House Number"] == 849) & (dataset["Zipcode"] == "14209.0") & (dataset["Street"] == "DELAWARE"),
]

indexes = []
for condition in conditions:
    indexes.extend(dataset.index[condition])

# Print the indexes
print(indexes)

[19766, 21535, 28345, 31826, 32489, 34175, 365, 425, 868, 1219, 1429, 1473, 1675, 2117, 2270, 2629, 2671, 3219, 4201, 4822, 4837, 4949, 5406, 5644, 5653, 5750, 6360, 6576, 6761, 6767, 8424, 10018, 10178, 11013, 11103, 11142, 11453, 11484, 11521, 11543, 11932, 12245, 12471, 12773, 12836, 12861, 13102, 13151, 13343, 4093, 9531, 14124, 14763, 15290, 16858, 17240, 21359, 22588, 25302, 25893, 15550, 22659, 25844, 26473, 27905, 29924, 33164, 33385, 33696, 329, 808, 1959, 2510, 5236, 10003, 12008, 12171, 402, 799, 3996, 4064, 4896, 6688, 7614, 11258, 12917, 11752, 13996, 14267, 14527, 14919, 15320, 16929, 16932, 16945, 18258, 18677, 18903, 19630, 20464, 20627, 20847, 21176, 21232, 22933, 23724, 25228, 26295, 1184, 1630, 2311, 3085, 3727, 4223, 7900, 8223, 10062, 11538, 15731, 17113, 17295, 17994, 20814, 25217, 25359, 25432, 26565, 26697, 28167, 28297, 28764, 28819, 28820, 28973, 29105, 29194, 30129, 30938, 31027, 32450, 32924, 33297, 33553, 34121, 34919, 2018, 2380, 2482, 3153, 3564, 7870, 11273, 12213, 256, 5968, 6736, 11139, 11862, 13543, 13755, 13853, 14381, 14536, 14678, 14901, 15048, 15268, 16183, 16642, 16797, 17808, 17872, 18004, 18042, 18062, 18384, 18610, 19067, 19082, 19143, 19200, 19361, 19650, 19707, 19741, 20562, 20583, 21055, 21486, 21803, 21844, 22465, 22577, 22796, 23439, 23907, 24642, 24896, 25282, 25387, 25929, 415, 683, 727, 1000, 2697, 2935, 3799, 3821, 4208, 5898, 7257, 8354, 8562, 10985, 11844, 312, 703, 756, 854, 915, 1224, 1225, 1569, 1827, 2076, 2278, 2364, 2421, 2664, 2754, 3478, 3479, 3914, 4173, 4917, 4932, 4934, 4964, 5058, 5231, 5769, 6202, 6267, 6460, 6511, 6673, 6883, 6891, 6910, 6997, 7020, 7033, 7231, 7390, 7788, 8081, 8462, 8522, 8820, 9006, 9285, 9304, 9315, 9461, 9555, 9758, 9860, 9896, 10065, 10622, 11055, 11342, 11831, 12582, 12637, 12715, 12992, 13193, 13349, 32597, 33437, 16075, 16511, 18256, 18292, 21108, 22453, 24125, 25175, 26709, 16274, 19770, 20196, 21086, 21296, 27355, 27370, 27423, 27718, 27838, 28765, 29258, 30559, 32016, 32723, 32812, 32876, 32923, 33037, 33895, 34371, 34434, 35316, 934, 3298, 9689, 10030, 11471, 12486, 13470, 13859, 14089, 14358, 14457, 14636, 14958, 15450, 15763, 15918, 16810, 17242, 18023, 18205, 18834, 19091, 19154, 19212, 19929, 19954, 20111, 20579, 20582, 21039, 21219, 21404, 21540, 21579, 21828, 22153, 22263, 22587, 22757, 22811, 23160, 23203, 23737, 24258, 25412, 25584, 25728, 26083, 26229, 494, 1165, 2181, 2954, 3115, 3389, 3695, 5071, 5156, 5342, 5554, 6368, 7203, 7217, 7534, 7619, 9224, 10426, 10493, 10956, 11329, 11332, 11889, 12157, 12764, 289, 459, 547, 563, 959, 1838, 1994, 2465, 2681, 2696, 2783, 2851, 3152, 3445, 3631, 3820, 3833, 3918, 4047, 4094, 4144, 4668, 4743, 4816, 4832, 5735, 6293, 6472, 6834, 6905, 7512, 7933, 8312, 8592, 8709, 8796, 8877, 9049, 9082, 9424, 9790, 9849, 10505, 10854, 11027, 11389, 11848, 11890, 11892, 12142, 12533, 12726, 13363, 13744, 13901, 14550, 15972, 16302, 17051, 20532, 21336, 21417, 22219, 23373, 24721, 25592, 26355, 26456, 820, 1322, 3785, 4303, 4399, 6091, 6563, 6956, 6979, 7032, 7283, 7301, 7484, 7644, 9037, 9872, 9946, 10302, 10767, 10772, 11725, 11836, 11939, 12841, 12868, 12976, 13132, 108, 116, 406, 429, 450, 701, 882, 956, 958, 1147, 1204, 1212, 1230, 1319, 1350, 1526, 1703, 1770, 1789, 1826, 1854, 1908, 1911, 1943, 1993, 2168, 2237, 2363, 2420, 2422, 2429, 2532, 2710, 2796, 3102, 3176, 3203, 3217, 3514, 3524, 3572, 3660, 3667, 3673, 3678, 3692, 3700, 3746, 3873, 3940, 4041, 4138, 4155, 4181, 4220, 4264, 4279, 4413, 4419, 4438, 4587, 4606, 4641, 4715, 4729, 4828, 4898, 5084, 5128, 5136, 5350, 5387, 5464, 5480, 5493, 5697, 5805, 5946, 5967, 5978, 6127, 6199, 6211, 6265, 6309, 6343, 6419, 6420, 6506, 6646, 6647, 6734, 6740, 6747, 6845, 6861, 6975, 6984, 7089, 7268, 7500, 7505, 7532, 7608, 7623, 7703, 7710, 7724, 7747, 7820, 7904, 7910, 7936, 7938, 7942, 7951, 7986, 8065, 8119, 8209, 8212, 8289, 8353, 8357, 8471, 8505, 8624, 8662, 8694, 8705, 8831, 8897, 8957, 9101, 9114, 9200, 9227, 9239, 9251, 9350, 9420, 9428, 9453, 9503, 9539, 9641, 9687, 9702, 9705, 9735, 9764, 9821, 9829, 9837, 9892, 9940, 9999, 10014, 10148, 10250, 10251, 10401, 10430, 10491, 10571, 10595, 10659, 10721, 10744, 10753, 10843, 10857, 10940, 11007, 11032, 11096, 11111, 11120, 11149, 11159, 11228, 11263, 11267, 11309, 11340, 11368, 11443, 11492, 11510, 11528, 11822, 11935, 11968, 12018, 12020, 12133, 12134, 12136, 12148, 12219, 12288, 12293, 12333, 12435, 12537, 12548, 12562, 12565, 12691, 12716, 12720, 12749, 12821, 12843, 12849, 12972, 13057, 13068, 13179, 13181, 13207, 13229, 13306, 13317, 13374, 13395, 7501, 8300, 8387, 13715, 16110, 16263, 16623, 16870, 16988, 17000, 20492, 21659, 21713, 22377, 22753, 25620, 25950, 26327, 217, 468, 565, 606, 759, 1573, 2006, 2456, 2688, 2873, 3222, 3403, 4184, 5043, 5326, 5334, 5502, 5567, 5753, 5808, 5812, 6151, 6484, 6712, 6965, 7303, 8038, 8087, 8912, 9168, 9324, 9479, 10183, 10547, 10627, 10840, 11040, 11750, 11902, 12127, 12503, 12990, 13419]

In [64]:
dataset = dataset.drop(indexes)

In [65]:
dataset.shape

(24230, 35)

In [67]:
# Filter the dataset based on the condition
filtered_data = dataset[ (dataset["House Number"] == 216) & (dataset["Zipcode"] == "14222.0") & (dataset["Street"] == "SUMMER")]

# Display the filtered data
print(filtered_data)

Empty DataFrame
Columns: [SBL, Tax District, Front, Depth, Property Class, Property Class Description, Owner1, Previous Owner, Mail3, Mail4, House Number, Street, Address, City, State, Zipcode, Deed Book, Deed Page, Deed Date, Roll, Land Value, Total Value, Sale Price, First Story Area, Second Story Area, Total Living Area, Council District, Police District, Census Tract, Census Block Group, Census Block, Neighborhood, Latitude, Longitude, Index]
Index: []

[0 rows x 35 columns]

In [68]:
# Table 1: OWNER info
owner_info = dataset[["Owner1", "Previous Owner", "Mail3", "Mail4"]]

# Table 2: House info
address_info = dataset[["House Number", "Street", "Zipcode","SBL"]]

#Table 3: Zipcode table
zipcode_info = dataset[["Zipcode","State","City"]]

# Table 4: Deed info
deed_info = dataset[["Deed Book", "Deed Page", "Deed Date", "Roll"]]

#table 5:Census table
census_info =  dataset[["Census Tract"]]

# Table 6: Property details
property_info = dataset[["SBL", "Front", "Depth", "Property Class", "Total Living Area"]]

#Table 7: Property class table
property_class_info = dataset[["Property Class","Property Class Description"]]

# Table 8: Price details
price_info = dataset[["Land Value", "Total Value", "Sale Price"]]

# Generating surrogate primary keys
owner_info['Owner_ID'] = dataset["Index"]
deed_info['Deed_ID'] = dataset["Index"]
price_info['Price_ID'] = dataset["Index"]
census_info['Census_ID'] = dataset["Index"]

#Table 9: link table
link_table = pd.DataFrame({
    "SBL": property_info["SBL"],
    "Owner_ID": owner_info["Owner_ID"],
    "Deed_ID": deed_info["Deed_ID"],
    "Price_ID": price_info["Price_ID"],
    "Census_ID": census_info["Census_ID"]
})

C:\Users\sahit\AppData\Local\Temp\ipykernel_16732\3265880116.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  owner_info['Owner_ID'] = dataset["Index"]
C:\Users\sahit\AppData\Local\Temp\ipykernel_16732\3265880116.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deed_info['Deed_ID'] = dataset["Index"]
C:\Users\sahit\AppData\Local\Temp\ipykernel_16732\3265880116.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price_info['Price_ID'] = dataset["Index"]
C:\Users\sahit\AppData\Local\Temp\ipykernel_16732\3265880116.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  census_info['Census_ID'] = dataset["Index"]

In [69]:
# Save owner_info to CSV
owner_info.to_csv('owner_info.csv', index=False)

# Save address_info to CSV
address_info.to_csv('address_info.csv', index=False)

# Save zipcode_info to CSV
zipcode_info.to_csv('zipcode_info.csv', index=False)

# Save deed_info to CSV
deed_info.to_csv('deed_info.csv', index=False)

# Save census_info to CSV
census_info.to_csv('census_info.csv', index=False)

# Save property_info to CSV
property_info.to_csv('property_info.csv', index=False)

# Save price_info to CSV
price_info.to_csv('price_info.csv', index=False)

# Save link_table to CSV
link_table.to_csv('link_table.csv', index=False)

In [70]:
zipcode_info = zipcode_info.groupby('Zipcode').agg({'State': 'first', 'City': 'first'}).reset_index()
zipcode_info.to_csv('zipcode_info.csv', index=False)

# Save property_class_info to CSV
property_class_info = property_class_info.groupby('Property Class').agg({'Property Class Description': 'first'}).reset_index()
property_class_info.to_csv('property_class_info.csv', index=False)